CREATE SCHEMA IF NOT EXISTS `stocks` DEFAULT CHARACTER SET latin1 
USE `stocks`;

-- Host: 52.32.212.110    Database: stocks

--
-- Table structure for table `COMPANY`
--

CREATE  TABLE IF NOT EXISTS `stocks`.`COMPANY` (
  `SYMBOL` VARCHAR(10) NOT NULL ,
  `NAME` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`SYMBOL`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1

--
-- Table structure for table `QUOTES`
--

CREATE  TABLE IF NOT EXISTS `stocks`.`QUOTES` (
  `SYMBOL` VARCHAR(10) NOT NULL ,
  `STOCK_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `ASK` DOUBLE NULL DEFAULT NULL ,
  `BID` DOUBLE NULL DEFAULT NULL ,
  PRIMARY KEY (`SYMBOL`, `STOCK_TIME`) ,
  INDEX `FK_SYMBOL_idx` (`SYMBOL` ASC) ,
  CONSTRAINT `FK_SYMBOL`
    FOREIGN KEY (`SYMBOL` )
    REFERENCES `stocks`.`COMPANY` (`SYMBOL` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1